# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
  autofix_commit_msg: '[pre-commit.ci] auto fixes'
  autofix_prs: true
  autoupdate_schedule: monthly
  autoupdate_commit_msg: 'chore(deps): pre-commit autoupdate'
  skip:
  - check-dependabot

default_language_version:
  python: python3.11

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.28.1
  hooks:
  - id: check-dependabot
  - id: check-github-workflows
  - id: check-readthedocs

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.3.4
  hooks:
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix]
  - id: ruff-format

- repo: https://github.com/tox-dev/pyproject-fmt
  rev: "1.7.0"
  hooks:
  - id: pyproject-fmt

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.9.0
  hooks:
  - id: mypy
    additional_dependencies:
    - typing-extensions
    - sqlalchemy[mypy]
