# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
  autofix_commit_msg: '[pre-commit.ci] auto fixes'
  autofix_prs: true
  autoupdate_schedule: monthly
  autoupdate_commit_msg: 'chore(deps): pre-commit autoupdate'

default_language_version:
  python: python3.11

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.27.3
  hooks:
  - id: check-dependabot
  - id: check-github-workflows
  - id: check-readthedocs

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.1.9
  hooks:
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix]

- repo: https://github.com/psf/black
  rev: 23.12.1
  hooks:
  - id: black

- repo: https://github.com/tox-dev/pyproject-fmt
  rev: "1.5.3"
  hooks:
  - id: pyproject-fmt

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.8.0
  hooks:
  - id: mypy
    additional_dependencies:
    - typing-extensions
    - sqlalchemy[mypy]

- repo: https://github.com/pycqa/flake8
  rev: 6.1.0
  hooks:
  - id: flake8
