[build-system]
build-backend = "poetry.core.masonry.api"
requires = [
  "poetry-core>=2,<3",
]

[tool.poetry]
name = "tap-athena"
version = "1.4.0"
description = "`tap-athena` is a Singer tap for Athena, built with the Meltano Singer SDK."
license = "Apache-2.0"
authors = [
  "AJ Steers <aaronsteers@gmail.com>",
  "Pat Nadolny <pat@meltano.com>",
]
maintainers = [
  "Metano Team and Contributors <hello@meltano.com>",
]
readme = "README.md"
keywords = [
  "Athena",
  "ELT",
]
packages = [
  { include = "tap_athena" },
]
dependencies.python = ">=3.10"
dependencies.pyathena = ">=3,<4"
dependencies.singer-sdk = "~=0.54.5"
group.dev.dependencies.coverage = ">=7.3.2"
group.dev.dependencies.moto = ">=5.0.0"
group.dev.dependencies.pytest = ">=8.0.0"
extras.s3 = [
  "fs-s3fs",
]
# CLI declaration
scripts.tap-athena = "tap_athena.tap:TapAthena.cli"

[tool.ruff]
target-version = "py310"
line-length = 88
lint.select = [
  "A",
  "ANN",
  "ARG",
  "B",
  "BLE",
  # "CPY",
  "C4",
  "C90",
  "COM",
  "D",
  "DTZ",
  "E",
  "EM",
  "ERA",
  "F",
  "FA",
  "FBT",
  "FIX",
  "FLY",
  "G",
  "I",
  "ICN",
  "INP",
  "ISC",
  "N",
  "PERF",
  "PGH",
  "PIE",
  "PL",
  "PT",
  "PTH",
  "Q",
  "RET",
  "RSE",
  "RUF",
  # "ASYNC",
  "S",
  "SIM",
  "SLF",
  "T10",
  "T20",
  "TCH",
  "TD",
  "TID",
  "TRY",
  "UP",
  "W",
  "YTT",
]
lint.ignore = [
  "ANN101", # missing-type-self
  "FIX002", # line-contains-todo
  "TD002",  # missing-todo-author
]
lint.per-file-ignores."tests/*" = [
  "S101",
]
lint.unfixable = [
  "ERA", # commented-out-code
]
lint.flake8-import-conventions.banned-from = [
  "typing",
]
lint.flake8-import-conventions.extend-aliases.typing = "t"
lint.isort.required-imports = [
  "from __future__ import annotations",
]
lint.pydocstyle.convention = "google"

[tool.mypy]
python_version = "3.10"
plugins = [
  "sqlalchemy.ext.mypy.plugin",
]
warn_unused_configs = true

[tool.pytest]
ini_options.filterwarnings = [ "error", "ignore::sqlalchemy.exc.SADeprecationWarning" ]
