[tool.poetry]
name = "tap-athena"
version = "0.0.1"
description = "`tap-athena` is a Singer tap for Athena, built with the Meltano SDK for Singer Taps."
authors = ["AJ Steers"]
license = "Apache 2.0"

[tool.poetry.dependencies]
python = "<3.10,>=3.6.2"
requests = "^2.25.1"
pyathena = "^2.3.0"

# Uncomment just one of the following sdk declarations.
# Note the prerelease SQLStream support is tracked here: https://gitlab.com/meltano/sdk/-/merge_requests/44

# singer-sdk = { git = "https://gitlab.com/meltano/sdk.git", branch = "74-database-type-streams" }
# singer-sdk = { path = "../sdk", develop = true }
singer-sdk = "^0.3.12"
sqlalchemy = {version = "^1.4", extras = ["sqlalchemy"]}

[tool.poetry.dev-dependencies]
pytest = "^6.1.2"
flake8 = "^3.9.2"
mypy = "^0.910"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
# CLI declaration
tap-athena = 'tap_athena.tap:TapAthena.cli'
